### PR TITLE
fix map/flatten to stop ignoring the value `false`.

### PR DESCRIPTION
**Pull request by weissjeffm**
Fixes https://github.com/plumatic/plumbing/issues/135 - see that issue for details.

### CODE REVIEW

**Comment by w01fe** [comment]
Sorry, I didn't get a notification about your followup commit and lost track of this.

**Comment by w01fe** [comment]
Really sorry about that.  If you are up for fixing conflicts and leave a comment afterwards I will merge right away, but understand if you're not up for it.

**Comment by weissjeffm** [comment]
I rebased, you can try merging now

**Comment by w01fe** [comment]
Thanks!  Merged as #146

**Pull request closed without merging**
